[postgres]
connection_string = "postgresql://postgres:[YOUR-PASSWORD]@db.lqjayksoihbnsfcfotxy.supabase.co:5432/postgres"

[supabase]
url = "https://lqjayksoihbnsfcfotxy.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxamF5a3NvaWhibnNmY2ZvdHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Njg5NTgsImV4cCI6MjA2NjI0NDk1OH0.tgU71GAVMWgL-jFKE2nIQHlK00Pz89w-9syu0suFZCA"